### ISSUE TITLE
looking more like epiphany. 

### ISSUE THREAD

**Issue by damianlang** [chpii/Headerbar#21] opened 2015-10-28 18:36 UTC
i should have contacted you here, heres my post: http://forum.userstyles.org/discussion/47343/x

made a heap of changes to make it more like epiphany which style i like. want my code or want me to do my own version that's different? depends what you're into :)

**Comment by damianlang** [comment] 2015-10-28 18:44
#urlbar, #searchbar {
        height: 34px;
        text-align: center;
        border: none !important; 
        margin: 0px 0 !important; 
        padding: 0px !important; 
        border-radius: 0px !important; 
        box-shadow: none !important;
        -moz-appearance: none !important; 
        visibility: visible !important; 
        border: none !important; 
        border-collapse:collapse!important; 
        background: none transparent !important;
    }
    
    
            #urlbar[focused="true"], #searchbar[focused="true"] {
                background: linear-gradient(to bottom, #383b3b, #333434)!important;
        box-shadow: inset 0 1.5px #2d3232, inset 0 -1.5px #4e5353!important;
                border-radius: 3px 3px 3px 3px!important;
                border-style: solid!important;       
                border-width: 1px!important;
                border-color: #4574db!important;

}

**Comment by DoctorJellyface** [comment] 2015-10-28 18:58
Hey, seems nice, thanks for making it. Just a few things:
* could it be possible to split the title into two lines, with a bigger bold font for the title and smaller normal font for the URL?
* could you change it from mouseover to mouseclick, as in epiphany? Also, is it possible to drag the window by it?

Thanks again.

**Comment by chpii** [comment] 2015-10-28 19:41
This is a duplicate of #13.

I will try to work on that issue.

Wait for an update this Friday, if not happening - next Friday.

**Closed by chpii** 2015-10-28 19:41 UTC
Labels: enhancement, help wanted
